server:
  port: 8080
spring:
  application:
    name: confirm
  rabbitmq:
    host: 192.168.47.128
    username: admin
    password: 123456
    virtual-host: powernode
    # 开启队列确认机制
    publisher-returns: true