server:
  port: 8080
spring:
  application:
    name: reliability
  rabbitmq:
    host: 192.168.47.128
    username: admin
    password: 123456
    virtual-host: powernode
    #开启队列确认模式
    publisher-returns: true
    #开启交换机确认模式
    publisher-confirm-type: correlated
  redis:
    host: 192.168.0.106
    database: 0